### ISSUE TITLE
ffmpeg issue

### ISSUE THREAD

**Issue by neodada** [Maxstupo/ydl-ui#1]
I am trying to download a video from regional site which is supported by youtube-dl. But YDL-ui is not able to dowload. Here is screenshot
https://i.imgur.com/6boTC6S.png.

But if i replace ffmpeg from some other app then it works. Maybe you need to update ffmpeg?
Site: https://www.hotstar.com/

**Comment by Maxstupo** [comment]
Works for v1.4.2

```
[HotStar] 2001616875: Downloading JSON metadata
[HotStar] 2001616875: Downloading JIO JSON metadata
[HotStar] 2001616875: Downloading m3u8 information
[download] Destination: VOD-2001616875.mp4
ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, hls,applehttp:
  Duration: 00:01:22.84, start: 2.160222, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:VOD-2001616875.mp4.part':
  Metadata:
    encoder         : Lavf58.12.100
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 2071 fps= 24 q=-1.0 Lsize=   46169kB time=00:01:22.83 bitrate=4566.0kbits/s speed=0.972x
video:45501kB audio:648kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.044456%
[ffmpeg] Downloaded 47276832 bytes
[download] 100% of 45.09MiB in 01:33
```

**Comment by neodada** [comment]
I have tried again and there is some error at end. How can i pause that to copy error?

**Comment by neodada** [comment]
`
[HotStar] 2001616883: Downloading JSON metadata
[HotStar] 2001616883: Downloading JIO JSON metadata
[HotStar] 2001616883: Downloading m3u8 information
[download] Destination: VOD-2001616883.mp4
ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3
 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv
 --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --e
nable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable
-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheor
a --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --ena
ble-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --e
nable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-am
rwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --e
nable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --e
nable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[tls @ 00a0eb40] Error in the pull function.
https://hssportsprepack.akamaized.net/videos/cricket/indvireveng2018/22_08_2018/
2001616883/master_Layer4.m3u8: I/O error


ERROR: ffmpeg exited with code 1

D:\ydl\bin>`

**Comment by Maxstupo** [comment]
It's an issue related to ffmpeg or youtube-dl not YDL-UI.
