### ISSUE TITLE
Downloading audio-only from playlist randomly doesn't convert to audio after downloading video

### ISSUE THREAD

**Issue by DaforLynx** [Maxstupo/ydl-ui#100]
Settings used:
144p Video Quality
24 FPS
No Overwrites
Ignore Errors
Audio Only (MP3)
Add metadata
Max concurrent downloads -> 1

Browsing through the output folder after downloading the playlist, it seems like a few videos (5/89 of them) escaped being converted to audio after being converted to video. Is this an issue with yt-dl or this front-end?
Also, feature request to 1) have a dropdown for audio file bitrate/quality and 2) _not_ download the video before converting to audio (not sure if that's possible)

**Comment by Maxstupo** [comment]
> Settings used:
> 144p Video Quality
> 24 FPS
> No Overwrites
> Ignore Errors
> Audio Only (MP3)
> Add metadata
> Max concurrent downloads -> 1
> 
> Browsing through the output folder after downloading the playlist, it seems like a few videos (5/89 of them) escaped being converted to audio after being converted to video. Is this an issue with yt-dl or this front-end?

Based on the settings and the fact that only a few videos didn't get converted, it sounds like an issue with yt-dl. 


>  feature request to 1) have a dropdown for audio file bitrate/quality and 2) not download the video before converting to audio (not sure if that's possible)

Both features are already planned to be in v3.0 of YDL-UI.
