### ISSUE TITLE
Save user interface and list of downloads

### ISSUE THREAD

**Issue by papin1** [Maxstupo/ydl-ui#101]
Hi,

Each time the program starts, I have to resize the window to its last size when it is not maximized.
Then, I have to resize the width of each column of the list of downloads, because to me the most important is the title of the video, not its URL which doesn't convey any meaning especially on youtube.

So, I would like some of the interface properties to be restored on startup. There might exist other settings worth of saving but I would be happy with the 2 ones above. Best way IMHO is some sort of config.ini within the application folder (to ensure portability).

As a further enhancement, I also would like to be able to save the list of downloads, so that I can track them and avoid downloading more than once --- since after they are downloaded the videos are dispatched to other folders or disks. Another reason may be that if the video is lost for whatever cause (e.g. hard drive failure) I can download it again.

FYI, your program is much less convoluted than the needlessly complicated tartube (I know a little bit of python but not C#). The binary yt-dlp_x86.exe (https://github.com/yt-dlp/yt-dlp, and yes I still use Win 7 x32) works very well excepted for the automated subtitles.

Best regards.

**Comment by MatheusOliveira-dev** [comment]
Hey @papin1.

I created PR #103

Can you check it out later?

**Comment by Maxstupo** [comment]
@papin1 
> As a further enhancement, I also would like to be able to save the list of downloads, so that I can track them and avoid 
> downloading more than once --- since after they are downloaded the videos are dispatched to other folders or disks. Another 
> reason may be that if the video is lost for whatever cause (e.g. hard drive failure) I can download it again.

You can use the download archive feature. It creates a text file containing a list of downloaded URLs. Option is in the Add Download dialog (with basic mode unchecked).
https://github.com/Maxstupo/ydl-ui/wiki/Interface#download-archive


> Each time the program starts, I have to resize the window to its last size when it is not maximized.
> Then, I have to resize the width of each column of the list of downloads, because to me the most important is the title of the video, not its URL which doesn't convey any meaning especially on youtube.
> 
> So, I would like some of the interface properties to be restored on startup. There might exist other settings worth of saving but I would be happy with the 2 ones above. Best way IMHO is some sort of config.ini within the application folder (to ensure portability).

I already added column width saving in an earlier version (see #49), but it had a number of issues (#79, #67), so it was removed. Until the issues are fixed, the feature can't be added.
