### ISSUE TITLE
 all the links inserted all migrate to youtube

### ISSUE THREAD

**Issue by Davide2009** [Maxstupo/ydl-ui#105]
**if I paste a link other than youtube it does not open, all the links inserted all migrate to youtube fake link**

example: _https://www.raiplay.it/video/2022/03/Serie-A-2021-2022---Roma-Atalanta---05-03-2022-b5a2bf83-6bac-430b-86a3-d33e24a678e2.html_

Click link Result: _https://www.youtube.com/watch?v=https%3A%2F%2Fwww_

**Comment by MatheusOliveira-dev** [comment]
Are you using any version directly from AppVeyor?

**Comment by MatheusOliveira-dev** [comment]
Or from Github releases?

If yes, which version?

**Comment by Davide2009** [comment]
Github
