### ISSUE TITLE
Restricted YouTube videos cannot be downloaded / Login fails

### ISSUE THREAD

**Issue by Nevetos** [Maxstupo/ydl-ui#107]
Any youtube restricted content which needs logging in will not download. (Or login fails?)

Log entry:
```
Working Directory: C:\Users\******\Videos
YDL Version: 2.9.0

Executing: C:\Program Files\YDL-UI_v2.9.0.0_Portable\bin\youtube-dl.exe --ignore-errors --ignore-config --no-overwrites --no-cache-dir --write-thumbnail --format "bestvideo[height=?1080][fps=?30]+bestaudio/bestvideo[height=?1080][fps=?25]+bestaudio/bestvideo[height=?1080][fps=?24]+bestaudio/bestvideo[height=?720][fps=?30]+bestaudio/bestvideo[height=?720][fps=?25]+bestaudio/bestvideo[height=?720][fps=?24]+bestaudio/bestvideo[height=?480][fps=?30]+bestaudio/bestvideo[height=?480][fps=?25]+bestaudio/bestvideo[height=?480][fps=?24]+bestaudio/bestvideo[height=?360][fps=?30]+bestaudio/bestvideo[height=?360][fps=?25]+bestaudio/bestvideo[height=?360][fps=?24]+bestaudio/bestvideo[height=?240][fps=?30]+bestaudio/bestvideo[height=?240][fps=?25]+bestaudio/bestvideo[height=?240][fps=?24]+bestaudio/bestvideo[height=?144][fps=?30]+bestaudio/bestvideo[height=?144][fps=?25]+bestaudio/bestvideo[height=?144][fps=?24]+bestaudio/bestvideo[height<=?1080][fps<=?30]+bestaudio/best" --username "AUsernameWasHere" --password "APasswordWasHere" --prefer-ffmpeg --ffmpeg-location "C:\Program Files\YDL-UI_v2.9.0.0_Portable\bin\ffmpeg\ffmpeg.exe"  "https://www.youtube.com/watch?v=d1TnAnqOpzA&ab_channel=Police%D0%A1hase"

[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] d1TnAnqOpzA: Downloading webpage
[youtube] d1TnAnqOpzA: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.

```

 - YDL-UI Version:  v2.9.0
 - OS: Windows 11 (pls don't judge)

**Comment by Nevetos** [comment]
And I have found a solution. It was already possible, just not explained well.

For anyone wanting to know:

1. Get the chrome extension [https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en](url)
2. Go to [https://www.youtube.com/](url) & login with your account. Grab the cookie txt file.
3. Go to [https://myaccount.google.com/](url) & login with your account. Grab the cookie txt file.
4. Combine both into a txt, making sure to have the following at the top of the txt file:
`# Netscape HTTP Cookie File
# This file is generated by youtube-dl.  Do not edit.

`
5. In YDL-UI when you want to download a new video:
a) Un-select basic mode
b) Go to 'Workarounds' tab
c) Tick 'Cookies:' and link to the cookies file.
d) Tick 'Username' under 'Authentication' and put in login details.

**Comment by Maxstupo** [comment]
That is the main solution that I know of. I don't think you need to include step 3 or add your login details. Just the cookies from YouTube should be enough.
