### ISSUE TITLE
Clicking on '...' button causes UI to shrink in size

### ISSUE THREAD

**Issue by raelb** [Maxstupo/ydl-ui#108]
When clicking on the '...' button in Add url or in settings it causes the entire UI to snap and shrink in size.
Initially the UI is not high dpi aware (i.e. the ui is slightly blurred).
When clicking on the button, the ui becomes more crisp, but tiny.

https://user-images.githubusercontent.com/13108198/167445597-26b58d49-ae73-4f78-bd20-abe996e44d65.mp4

**Information (please complete the following information)**
 - YDL-UI Version: 2.9.0
 - OS: Windows 10 x64
 - - Screen resolution: 150% scaling

**Comment by raelb** [comment]
Possible solutions:
https://stackoverflow.com/questions/42975285/commonopenfiledialog-cause-windows-form-to-shrink

**Comment by Maxstupo** [comment]
> Possible solutions: https://stackoverflow.com/questions/42975285/commonopenfiledialog-cause-windows-form-to-shrink

Attempted fix in #19, fix was later rolled back in #29 due to other display issues

**Comment by raelb** [comment]
It is not a big thing. I found problem solved by selecting "use basic folder picker"

![image](https://user-images.githubusercontent.com/13108198/175784299-c5490785-1624-495b-b673-d7063b827805.png)
