### ISSUE TITLE
Improvemnt - Add ffmpeg profiles to standard installation to convert file in MKV/MP4

### ISSUE THREAD

**Issue by bovirus** [Maxstupo/ydl-ui#11]
I think that could be useful for many users to find in the standard installation some ffmpeg profiles ready to use to convert typical YouTube file (.webm) in MP4/MKV file format (keeping resolution/frame rate)

Thanks.

**Comment by Maxstupo** [comment]
When adding a download you can specify the format the video will be converted to (It can be found under the post processing tab when basic mode is unchecked, for v2.0+).

If something more is needed or you need to convert videos that are already downloaded, a seperate application (e.g. HandBrake) will need to be used instead.
