### ISSUE TITLE
Download BBC video 1080p50 + no redirect

### ISSUE THREAD

**Issue by matteocrimi** [Maxstupo/ydl-ui#111]
Hi everyone, I'm new to github and don't have much knowledge of programming languages but... I observe and try to understand (and solve)!
(I apologize if this topic was already present elsewhere: administrators can redirect it)
________________________________________________________

**### Request: download BBC video in 1080p50 with YDL-UI (version 2021.12.17) by correctly setting in "custom format selector" the variables between [...], which also prevent its redirection.**

Sample link: https://www.bbc.co.uk/iplayer/episode/m001cqwp/the-state-funeral-of-hm-queen-elizabeth-ii-a-national-minutes-silence-for-hm-the-queen

I am currently using YDL-UI Version 2021.12.17.

As you can see in the log text below, between the 2nd and 3rd lines the media changes name (from "m001cqwp" to "m001cqwn"):

_[bbc.co.uk] m001cqwp: Downloading video page
[bbc.co.uk] m001cqwp: Downloading playlist JSON
[bbc.co.uk] m001cqwn: Downloading media selection JSON
[bbc.co.uk] m001cqwn: Downloading MPD manifest.
...
[bbc.co.uk] m001cqwn: Downloading MPD manifest.
[bbc.co.uk] m001cqwn: Downloading m3u8 information.
...
[bbc.co.uk] m001cqwn: Downloading m3u8 information.
[dashsegments] Total fragments: 19
[download] Destination: The State Funeral of HM Queen Elizabeth II, A National Minute's Silence for HM the Queen-m001cqwn.fmf_cloudfront-video=5070000-1.mp4_

Reading and matching the posts https://github.com/ytdl-org/youtube-dl/issues/30136 & https://github.com/yt-dlp/yt-dlp/issues/3463 (and particularly @edent 's expertise) I am convinced that it's possibile properly set YDL-UI for download 1080p50 videos (whose source perhaps is the media before the redirect in "Downloading media selection JSON"?)...

Thank you for any help you would like to offer to me

**Comment by Maxstupo** [comment]
The `custom format selector` in YDL-UI sets the [--format flag](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection) when calling youtube-dl. Support for different formats are handled by youtube-dl not YDL-UI.
