### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by Nevetos** [Maxstupo/ydl-ui#112]
It seems youtube changed an @ and this has broken everything.

The error is:
"[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] hePrs5TyE0A: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

However, it appears the underlying issue has already been found. (An extra @ in the userid)
https://forum.videohelp.com/threads/408650-No-longer-able-to-download-videos-with-youtube-dl-exe#post2681508
https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by Maxstupo** [comment]
This is primarily a problem with youtube-dl and not ydl-ui. 

Try using [v2.9.1](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.9.1) (see https://github.com/Maxstupo/ydl-ui/issues/114#issuecomment-1875614905) as v2.9.0 is bundled with an old youtube-dl version.
