### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [Maxstupo/ydl-ui#115]
Does this work with Win 7?

Thanks

**Comment by Maxstupo** [comment]
It should work. 

ydl-ui v2.9.1 and above requires .NET Framework v4.8 (or v4.5 for v2.9.0 and below). According to Microsoft, it should be installable on Windows 7.

[https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-48](https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-48)

**Comment by harryray33** [comment]
Thanks, yes, I've just remembered seeing somewhere that Win 7 is OK up to .NET 6.
