### ISSUE TITLE
Can't Download a Single YouTube Video From a Playlist

### ISSUE THREAD

**Issue by MithilMajumder** [Maxstupo/ydl-ui#13]
**Describe the bug**

When a single video's link is pasted from a playlist (also with index), YDL-GUI starts downloading the whole playlist instead of one which link is pasted.

**Information (please complete the following information)**
 - YDL-UI Version: 2.4.0
 - OS: Windows 10
 -  Architecture: x64

**Comment by Maxstupo** [comment]
Uncheck basic mode > video selection tab > video only.

![Video Only](https://i.gyazo.com/d0e70a8c21a79737f974438e612cde37.png)

**Comment by MithilMajumder** [comment]
Does it support downloading playlist from website requires login credentials such as SafariBooks - Oreilly Media
