### ISSUE TITLE
Can't download EJuxDbSkwmQ (download failed)

### ISSUE THREAD

**Issue by Smile4ever** [Maxstupo/ydl-ui#14]
**Describe the bug**
Downloading https://youtube.com/watch?v=EJuxDbSkwmQ doesn't work. I tried adding "www." but that also doesn't work. 

I tried different settings, but to no avail.

**To Reproduce**
Steps to reproduce the behavior (if applicable, attach preset file):
1. Add URL https://youtube.com/watch?v=EJuxDbSkwmQ
2. Download immediately

**Expected behavior**
MP4 or MP3 file is downloaded.

**Information**
 - YDL-UI Version: 2.4.0
 - OS: Windows 10
 -  Architecture: x64

**Comment by Maxstupo** [comment]
Please paste the download log text (Right click the download in the download list > View Log).

Are you using the portable or non-portable edition?

**Comment by Smile4ever** [comment]
Okay, I missed that option.

Log:

Working Directory: C:\Users\XYZ\Videos
Executing: C:\Users\XYZ\AppData\Local\Temp\YDL-UI.auhmerkw.1mc\youtube-dl.exe --no-overwrites --format "bestvideo[width<=?3840][height<=?2160][fps<=?144]+bestaudio/best[width<=?3840][height<=?2160][fps<=?144]" --extract-audio --audio-format mp3 --prefer-ffmpeg --ffmpeg-location "C:\Users\XYZ\AppData\Local\Temp\YDL-UI.auhmerkw.1mc\ffmpeg.exe"  "https://youtube.com/watch?v=HlALp2Z890Y"
[youtube] HlALp2Z890Y: Downloading webpage
ERROR: Unable to download webpage: <urlopen error Tunnel connection failed: 407 Proxy Authentication Required> (caused by URLError(OSError('Tunnel connection failed: 407 Proxy Authentication Required',),))


So it seems it cannot handle proxy servers; is this something you plan to fix or support?

**Comment by Maxstupo** [comment]
You can specify a proxy by going to the "workarounds" tab when adding a download (uncheck basic mode, bottom left corner).
This option supports HTTP/HTTPS/SOCKS proxies. To enable SOCKS proxy, specify a proper                               scheme. (e.g. socks5://127.0.0.1:1080/ )

If the above suggestion fails, I'm unable to fix or add support because this is a user interface for [youtube-dl](https://github.com/ytdl-org/youtube-dl). You might have better luck viewing the documentation or issues tracker for youtube-dl.

**Comment by Smile4ever** [comment]
I have used http://username:password@proxy.local:8080 and that gets me through the proxy.

Still doesn't download though.

```
C:\Users\XYZ\AppData\Local\Temp\YDL-UI.k1y3bh1i.30d\youtube-dl.exe --ignore-errors --proxy "http://XYZ:password@proxy.local:8080" --no-overwrites --format "bestvideo[width<=?3840][height<=?2160][fps<=?144]+bestaudio/best[width<=?3840][height<=?2160][fps<=?144]" --prefer-ffmpeg --ffmpeg-location "C:\Users\XYZ\AppData\Local\Temp\YDL-UI.k1y3bh1i.30d\ffmpeg.exe"  "https://youtube.com/watch?v=EJuxDbSkwmQ"
[youtube] EJuxDbSkwmQ: Downloading webpage
[youtube] EJuxDbSkwmQ: Downloading video info webpage
ERROR: EJuxDbSkwmQ: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Maxstupo** [comment]
I have released a new version of YDL-UI (v2.4.1) packaged with a newer youtube-dl version, this might fix the problem.

**Comment by Smile4ever** [comment]
That didn't work. Probably related to the proxy.

Working Directory: C:\Users\6061894\Videos
Execution: C:\Users\6061894\Downloads\YDL_UI_v2.4.1_Portable\bin\youtube-dl.exe --ignore-errors --proxy "http://6061894:zna-aanlog%40123@proxy.zna.local" --no-overwrites --format "bestvideo[width<=?3840][height<=?2160][fps<?144]+bestaudio/best[width<=?3840][height<=?2160][fps<=?144]". --Prefer-ffmpeg --ffmpeg-location "C:\Users\6061894\Downloads\YDL_UI_v2.4.1_Portable\bin\ffmpeg.exe" "https://youtube.com/watch?v=EJuxDbSkwmQ".
[youtube] EJuxDbSkwmQ: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not reply correctly after a certain time, or the connection made failed because the connected host did not reply > (caused by URLError(TimeoutError(10060, 'A connection attempt failed because the connected party did not reply correctly after a certain time, or the connection made failed because the connected host did not reply', None, 10060, None),)).

**Comment by Smile4ever** [comment]
Working Directory: C:\Users\XYZ\Videos
Execution: C:\Users\XYZ\Downloads\YDL_UI_v2.4.1_Portable\bin\youtube-dl.exe --ignore-errors --proxy "http://username:password@proxy.local" --no-overwrites --format "bestvideo[width<=?3840][height<=?2160][fps<?144]+bestaudio/best[width<=?3840][height<=?2160][fps<=?144]". --Prefer-ffmpeg --ffmpeg-location "C:\Users\XYZ\YDL_UI_v2.4.1_Portable\bin\ffmpeg.exe" "https://youtube.com/watch?v=EJuxDbSkwmQ".
[youtube] EJuxDbSkwmQ: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not reply correctly after a certain time, or the connection made failed because the connected host did not reply > (caused by URLError(TimeoutError(10060, 'A connection attempt failed because the connected party did not reply correctly after a certain time, or the connection made failed because the connected host did not reply', None, 10060, None),)).

**Comment by Smile4ever** [comment]
I tried with version 2.4.2 and that worked.
