### ISSUE TITLE
Clipboard Bug in YDL-UI 2.4.1 Portable

### ISSUE THREAD

**Issue by brunoalvieira** [Maxstupo/ydl-ui#15]
![Clipboarder 2019 05 04-002](https://user-images.githubusercontent.com/39491972/57186777-c3893680-6ebb-11e9-9481-4c9396b094a9.png)
[Debug.txt](https://github.com/Maxstupo/ydl-ui/files/3145020/Debug.txt)
![Clipboarder 2019 05 04-003](https://user-images.githubusercontent.com/39491972/57186830-4611f600-6ebc-11e9-87f8-20f73b909ebb.png)

I tried to use the link copy feature, but it did not work, with this error following attachment.

Details of the error can be found in the file Debug.txt

**Comment by Maxstupo** [comment]
This error is caused by another process using the clipboard. It will be fixed in the next commit.
