### ISSUE TITLE
Progress Bar Bug in YDL-UP 2.4.1 Portable

### ISSUE THREAD

**Issue by brunoalvieira** [Maxstupo/ydl-ui#16]
![Clipboarder 2019 05 04](https://user-images.githubusercontent.com/39491972/57186850-a1dc7f00-6ebc-11e9-925d-423270d49407.png)
[Log.txt](https://github.com/Maxstupo/ydl-ui/files/3145029/Log.txt)
As shown, the meter operates up to 1000%, while the log displays correctly.

In addition, apparently the behavior of the progress bar is not very clear, this is, whether its purpose is for total progress or for downloading video and then audio.

**Comment by Maxstupo** [comment]
The progress bar currently shows progress for each download component. This might be represented as the total progress if there is only one file, or two if the video and audio are separate files.

This was a compromise, as there was no easy way of determining the number of separate files that needed to be downloaded.
