### ISSUE TITLE
Command line arguments while running ydl-ui

### ISSUE THREAD

**Issue by iG8R** [Maxstupo/ydl-ui#18]
Hi.
Is it possible to add command line arguments while running ydl-ui?
E.g. [URL]:
**YDL-UI.exe url="https://www.youtube.com/watch?v=tFUDPRYHZ-E"**
and defined [URL] will be inserted into the URL field of the "Add Download..." dialog box or
**YDL-UI.exe url="https://www.youtube.com/watch?v=tFUDPRYHZ-E" \silent**
With "\silent" argument YDL-UI starts downloading in silent mode with previously used parameters (Download directory, Video quality etc.)
It would be very convenient while running it via browser Add-on "Open With" https://github.com/darktrojan/openwith

**Comment by Maxstupo** [comment]
I will look into adding this functionality. 

[youtube-dl](https://github.com/ytdl-org/youtube-dl) (the program YDL-UI uses) is a command-line program, might be worth looking into that in the meantime.

**Comment by iG8R** [comment]
Thank you.
I know concerning youtube-dl, pity, but it does not support memorizing the last used parameters, such as "Download directory", etc., or a convenient way to select them only by manual insertion.

**Comment by Maxstupo** [comment]
This feature is now in release [v2.5.0](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.5.0) (including /silent).

Example usage:
`YDL-UI.exe <url> [/silent]`
or
`YDL-UI.exe [/silent] <url>`
