### ISSUE TITLE
How can download audio only ?

### ISSUE THREAD

**Issue by XuRuoChang** [Maxstupo/ydl-ui#20]
https://www.youtube.com/watch?v=hRllLqrlHec

I tried to check the "Post Processing -> audio only -> m4a", but the size of the entire video file will still be downloaded. ( about 1002 MB)

If I use youtube-dl directly in cmd mode, just add the "-f 140" command to download only the audio, like "youtube-dl -f 140 https://www.youtube.com/watch?v=hRllLqrlHec"

The file format is m4a, of course the size is small. ( about 50 MB)

**Comment by Maxstupo** [comment]
Currently, this isn't possible.

The next update will include the ability to specify a custom format (-f command). 16c376ed0429c2130c2228ad2005a1e7a637bf90

**Comment by Maxstupo** [comment]
Release [v2.5.0](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.5.0) supports entering a custom format.

The equivalent "-f 140" command would be to type 140 into the custom format selector textbox (Uncheck basic mode).
