### ISSUE TITLE
2.5.0 [url] command line parameters' behaviour issue

### ISSUE THREAD

**Issue by iG8R** [Maxstupo/ydl-ui#21]
Hi. Thank you very much for such a quick implementation of command line parameter functionality.
I faced some misbehaviour this implementation shows: it doesn't matter whether I use "\silent" argument or not YDL-UI always downloads [url] without inquiring about "Download directory"where to save media, i.e. always uses silent-mode.
I thought while using:
YDL-UI.exe <url> - it'll invoke dialog box "Add download..."
YDL-UI.exe <url> [/silent] - it will not show dialogs and download [URL] using the last used parameters

PS. Please, can YDL-UI memorize the last used "Download directory"?

**Comment by Maxstupo** [comment]
Does the behaviour change if YDL-UI is closed vs already open, when running the commands?

The "/silent" option will still display the "Add download..." dialog, but will close very quickly after appearing (necessary for options to be applied).

The default download directory can be set in settings. Presets can be used for dynamic download directories based on video urls (preset gets selected if url pattern matches).

Note: When using "/silent", use a forward slash and not a backslash.

**Comment by iG8R** [comment]
Sorry for misguiding you - I reinstalled YDL-UI with the full erasing of previous version instead of overwriting and now YDL-UI works like it supposed to be:
YDL-UI.exe [url] - invokes dialog box "Add download..." not considering whether it is closed or not
YDL-UI.exe [url] /silent - adds download task and starts download

> Presets can be used for dynamic download directories based on video urls (preset gets selected if url pattern matches).

Yes, it's very convenient to have such presets, but at the same time it's also convenient to download first media into the desired folder with the desired settings (quality, etc.) and after that saving all other media with the same settings (quality, destination folder, etc.) that's why I asked YDL-UI to memorize last used parameters.
For example, using "Open with" addon and adding 2 commands to the context menu:
YDL-UI.exe %s
YDL-UI.exe %s /silent
+ memorizing last used parameters
+ already having "Presets"
it will cover all possible variations of utilizing YDL-UI.
