### ISSUE TITLE
Incorrect download location

### ISSUE THREAD

**Issue by hl2guide** [Maxstupo/ydl-ui#23]
**Describe the bug**
The "Add URL" dialog does not use the "Download Directory" if set on that dialog.
For me it just downloads to the default Windows download folder.

**To Reproduce**
Add a URL using the "download" menu item.

**Expected behavior**
The video downloads to the specified folder, not the default.

**Information**
 - YDL-UI Version: 2.5
 - OS: Windows 10
 -  Architecture: x64

**Comment by Maxstupo** [comment]
I'm unable to reproduce this.

Are you using the portable version?

**Comment by hl2guide** [comment]
Yes I'm using the portable version. I'll to reproduce this again in the next few days and record a GIF of it.

**Comment by hl2guide** [comment]
![example](https://user-images.githubusercontent.com/17044982/60324723-dbb39880-99c8-11e9-8e26-2bb1fe9ec83c.gif)

My ydl-ui.ini:

`
{
  "Version": 1,
  "CheckForUpdates": true,
  "PromptDownloadingOnClose": true,
  "BasicMode": true,
  "StayOnTop": false,
  "MaxConcurrentDownloads": 4,
  "ResumeDownloads": true,
  "DefaultDownloadArchive": "",
  "DefaultDownloadDirectory": "C:\\Temp\\Videos",
  "Binaries": {
    "youtube-dl": "bin\\youtube-dl.exe",
    "ffmpeg": "bin\\ffmpeg.exe"
  },
  "Presets": []
}
`

**Comment by Maxstupo** [comment]
Please paste the text from the download log (right click the download, view log)

**Comment by hl2guide** [comment]
Example Log: https://pastebin.com/gjivVZnp

**Comment by Maxstupo** [comment]
Does this problem occur when downloading to any other location? (e.g. Just to `C:\`)

**Comment by hl2guide** [comment]
Yes, tested and it's the same thing for: C:\

**Comment by hl2guide** [comment]
Fixed in v2.5.1 👍
