### ISSUE TITLE
New Features: Drag and Drop Support and Pasting

### ISSUE THREAD

**Issue by hl2guide** [Maxstupo/ydl-ui#24]
Please consider supporting a drag and drop to the main window with for one or many YouTube URLs.

Also being able to just paste URLs with the window active would be great.

Please allow users more batch adding ability.

**Comment by Maxstupo** [comment]
You can use a browser extension like [OpenWith](https://github.com/darktrojan/openwith) to add downloads. Just set a command within the extension e.g. `YDL-UI.exe <url> [/silent]`

Drag and drop for single urls is already supported. How would you drag and drop multiple urls?

**Comment by hl2guide** [comment]
For a single URL link when I try to drag drop it just shows a cross.
Dragging multiple links text from a notepad list would be a Clipboard text object.
Dragging a text file onto it could work too 💃

**Comment by Maxstupo** [comment]
Are you dragging the link onto the download list?

**Comment by hl2guide** [comment]
Yep, it is now working again in v2.5.1.
