### ISSUE TITLE
Download statistics not displayed in download list

### ISSUE THREAD

**Issue by iG8R** [Maxstupo/ydl-ui#29]
Hi. First of all, thank you very much for your great work.
Still observing an issue with DPI scaling (Resolution 3840x2160, Scaling - 150%).
And YDL-UI doesn't remember its last window size and position.
<img width="397" alt="2019-07-03_223228" src="https://user-images.githubusercontent.com/11407417/60620434-df3d8a00-9de3-11e9-88a8-876a8242a69d.png">

**Comment by Maxstupo** [comment]
The problem looks worse now compared to issue #19?

I have created a beta build of YDL-UI with the above referenced changes, it might fix the issue (please try the download directory button again).

[YDL_UI_v2.5.2-beta_Portable.zip](https://github.com/Maxstupo/ydl-ui/files/3373420/YDL_UI_v2.5.2-beta_Portable.zip)

**Comment by iG8R** [comment]
Yes, it's somehow worse than #19.
With YDL_UI_v2.5.2-beta_Portable.zip it's, I might say, OK, but as you can see on the screenshot fonts and lines are blur but all in all it's OK with some scaling issue remained. Thank you.
And there is still exists a problem with a progress, size, speed and ETA indicators.
<img width="1182" alt="2019-07-09_180240" src="https://user-images.githubusercontent.com/11407417/60900282-9b7bd200-a274-11e9-8a26-80bf78b380b4.png">

**Comment by Maxstupo** [comment]
The next release will contain these fixes, ensure that `Use Simple Folder Picker` is checked in settings.

Unfortunately, I'm unable to fix the DPI issue any further without rewriting YDL-UI (something I plan to do, but not in the near future).

**Comment by Maxstupo** [comment]
Download statistics not updating fixed in [v2.5.3](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.5.3).
