### ISSUE TITLE
Clearer Display for ETAs of Long Estimate Downloads

### ISSUE THREAD

**Issue by hl2guide** [Maxstupo/ydl-ui#33]
Please consider improving the display for downloads that have an ETA over 1 hour.

Currently it is like:
![screen](https://user-images.githubusercontent.com/17044982/61090748-0e5a9800-a483-11e9-8178-91e2086ec70e.png)

Shouldn't it have :00 on the end to denote seconds as a unit?

**Comment by Maxstupo** [comment]
Currently, `Progress`, `Size`, `Speed`, and `ETA` are all directly fetched from youtube-dl output. If I'm not mistaken the `ETA` is in `mm:ss` format.

**Comment by hl2guide** [comment]
hmm, might be worth looking into it as there is no way that I can download about 5GB in 1 minute and 53 seconds on a 11Mbps connection.

**Comment by Maxstupo** [comment]
![](https://i.gyazo.com/7f7a7fd5c4b143791611503fbb87e4eb.png)

It looks like `youtube-dl` outputs in `hh:mm:ss` only when the download time is above one hour, else `mm:ss`.

**Comment by hl2guide** [comment]
Makes sense. next time I'm downloading a big YouTube video I'll show more screenshots (results).

**Comment by hl2guide** [comment]
Another example of this issue:
![example](https://user-images.githubusercontent.com/17044982/62827669-1f7bfd80-bc17-11e9-9847-9ae7689f49c3.png)

**Comment by Maxstupo** [comment]
Made the `ETA` column only output `hh:mm:ss`
![](https://i.gyazo.com/bd7b96e55773357c631a09a6c63b6075.png)

**Comment by hl2guide** [comment]
wonderful thanks 🍰
