### ISSUE TITLE
Unable to extract video title

### ISSUE THREAD

**Issue by ssbroad** [Maxstupo/ydl-ui#34]
ydl-ui 2.5.2

filename template: %(title)s.%(ext)s

All videos can only be named "_.webm" because the video title could not be obtained

[youtube] iUYWYw00MlI: Downloading webpage
[youtube] iUYWYw00MlI: Downloading video info webpage
WARNING: Unable to extract video title
[download] Destination: _.f315.webm

my json
https://drive.google.com/open?id=1geyHbgK6PygzRNTQ40M2mJZIevUqKnu9

**Comment by Maxstupo** [comment]
Try updating `youtube-dl.exe` to the [latest version](https://github.com/ytdl-org/youtube-dl/releases/latest), by specifying the filepath (Settings > Binaries).

If you are using `YDL-UI Portable`, you can replace `bin/youtube-dl.exe` located in the same location as `YDL-UI.exe`.

**Comment by XuRuoChang** [comment]
thank you, i uplate youtube-dl to 08/02/2019, this issue has been resolved
