### ISSUE TITLE
Completed Download Size

### ISSUE THREAD

**Issue by hl2guide** [Maxstupo/ydl-ui#37]
Currently completed downloads show the audio component size not the total/final download size (larger) in the queue.

**Comment by Maxstupo** [comment]
I'm aware of this issue, but unfortunately there is no reliable way to determine if the size refers to the video/audio component, or an all-in-one video file.

**Comment by hl2guide** [comment]
Is it not possible to just get the final size of the output video after?

**Comment by Maxstupo** [comment]
No, not reliably.
