### ISSUE TITLE
"Add Download" Dialog Fixes

### ISSUE THREAD

**Issue by hl2guide** [Maxstupo/ydl-ui#4]
Please consider making the "add download" dialog have no maximize button and be fixed (not resizable). [highlighted in purple below]

![add download dialog](https://user-images.githubusercontent.com/17044982/49192450-3eab6580-f3cf-11e8-9579-960fe8383031.png)

 - YDL-UI Version: 2.0 (portable)
 - OS: Windows 10
 -  Architecture: x64

**Comment by Maxstupo** [comment]
Are you referring to the "Add Download" dialog when in basic mode or both?

**Comment by hl2guide** [comment]
Seems to only apply when basic mode is enabled (default, I think).

**Comment by Maxstupo** [comment]
I removed both minimize and maximize buttons, as I'm unable to remove just one. I also disabled the minimize button while in normal mode (as it remains resizable).

![4a9672741507e9982ee08c97690ebead](https://user-images.githubusercontent.com/6497952/49215699-78a35880-f41d-11e8-8b31-44ef689ad629.png)
