### ISSUE TITLE
Enable multi-language GUI

### ISSUE THREAD

**Issue by bovirus** [Maxstupo/ydl-ui#42]
@Maxstupo 

Thanks for your program.

Could you please consider to add the option to have multi-language GUI?

Thanks.

**Comment by bovirus** [comment]
@Maxstupo 

Thanks for the changes.

Could you please explain with details and include these info in readme how can translate the strings used by your program?

Thanks.

**Comment by Maxstupo** [comment]
[https://github.com/Maxstupo/ydl-ui_i18n](https://github.com/Maxstupo/ydl-ui_i18n)

**Comment by bovirus** [comment]
@Maxstupo 

Make a pull request on

https://github.com/Maxstupo/ydl-ui_i18n

with Italian translation file.
If you can please make a YDL-UI build to enable me to test the translation in place.
Thanks.

**Comment by Maxstupo** [comment]
@bovirus 

Release [v2.6.0](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.6.0)

The release doesn't include the Italian translation file (it will be added next release), so you will need to add the file to the `locales` folder manually (I recommend the portable edition for this).

**Comment by bovirus** [comment]
@Maxstupo 

Many thanks for the new release.

It could be the base for check the translation and also for other translator to create and check a new translation before to post in github repository.
