### ISSUE TITLE
A new guard page for the stack cannot be created

### ISSUE THREAD

**Issue by ssbroad** [Maxstupo/ydl-ui#44]
v2.6.0 can not start and show this message

windows 7

**Comment by Maxstupo** [comment]
Did you have this issue in [v2.5.3](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.5.3)?

**Comment by ssbroad** [comment]
> Did you have this issue in [v2.5.3](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.5.3)?

No

**Comment by kristofejro** [comment]
I have exactly the same issue.

**Comment by Maxstupo** [comment]
Please try [YDL-UI_Portable_v2.6.0-pb1.zip](https://github.com/Maxstupo/ydl-ui/files/3791942/YDL-UI_Portable_v2.6.0-pb1.zip), and let me know if the issue still occurs.

**Comment by kristofejro** [comment]
Now it seems to be fine.
It starts without a problem.

**Comment by Maxstupo** [comment]
@ssbroad 
> 
> 
> Please try [YDL-UI_Portable_v2.6.0-pb1.zip](https://github.com/Maxstupo/ydl-ui/files/3791942/YDL-UI_Portable_v2.6.0-pb1.zip), and let me know if the issue still occurs.

Is the problem fixed?

**Comment by ssbroad** [comment]
> @ssbroad
> 
> > Please try [YDL-UI_Portable_v2.6.0-pb1.zip](https://github.com/Maxstupo/ydl-ui/files/3791942/YDL-UI_Portable_v2.6.0-pb1.zip), and let me know if the issue still occurs.
> 
> Is the problem fixed?

fixed
