### ISSUE TITLE
Crash at application start

### ISSUE THREAD

**Issue by rolandbeck** [Maxstupo/ydl-ui#45]
Version=1
EventType=APPCRASH
EventTime=132168213078528285
ReportType=2
Consent=1
UploadTime=132168213586182494
ReportStatus=268435456
ReportIdentifier=d4e9df82-1e47-4b71-ace3-f8461e206004
IntegratorReportIdentifier=5de0eb71-b2e2-455c-bb2f-2e518f402884
Wow64Host=34404
Wow64Guest=332
NsAppName=YDL-UI.exe
OriginalFilename=YDL-UI.exe
AppSessionGuid=00000518-0001-0028-8155-8c1e4a8ed501
TargetAppId=W:0006f0b813758eb28d403f41c89a04b2f41c00000000!0000145534b9a1da69a50882c2a540e461eb83b88bae!YDL-UI.exe
TargetAppVer=2019//10//28:23:56:19!0!YDL-UI.exe
BootId=4294967295
ServiceSplit=1978925056
TargetAsId=331
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=fb3249595f73ffca467e3e05b1d06f9e
Response.BucketTable=1
Response.LegacyBucketId=1620801110078943134
Response.type=4
Sig[0].Name=Anwendungsname
Sig[0].Value=YDL-UI.exe
Sig[1].Name=Anwendungsversion
Sig[1].Value=2.6.0.0
Sig[2].Name=Anwendungszeitstempel
Sig[2].Value=5db78023
Sig[3].Name=Fehlermodulname
Sig[3].Value=clr.dll
Sig[4].Name=Fehlermodulversion
Sig[4].Value=4.8.4018.0
Sig[5].Name=Fehlermodulzeitstempel
Sig[5].Value=5d4a64a8
Sig[6].Name=Ausnahmecode
Sig[6].Value=c00000fd
Sig[7].Name=Ausnahmeoffset
Sig[7].Value=0001f646
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=10.0.18362.2.0.0.256.48
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=19a4
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=19a456ce44a74c224dad8dd0b8e76a49
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=74d2
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=74d2e3efdf109f7fd19b97e9220af7d2
UI[2]=D:\Users\<Username>\Desktop\YDL-UI.exe
LoadedModule[0]=D:\Users\<Username>\Desktop\YDL-UI.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[6]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\System32\sechost.dll
LoadedModule[8]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[9]=C:\WINDOWS\System32\SspiCli.dll
LoadedModule[10]=C:\WINDOWS\System32\CRYPTBASE.dll
LoadedModule[11]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[12]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
LoadedModule[13]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[14]=C:\WINDOWS\System32\combase.dll
LoadedModule[15]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[16]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[17]=C:\WINDOWS\System32\win32u.dll
LoadedModule[18]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[19]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[20]=C:\WINDOWS\System32\USER32.dll
LoadedModule[21]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[22]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[23]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[24]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
LoadedModule[25]=C:\WINDOWS\SYSTEM32\VCRUNTIME140_CLR0400.dll
LoadedModule[26]=C:\WINDOWS\SYSTEM32\ucrtbase_clr0400.dll
LoadedModule[27]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\mscorlib\bf92dcc11e428fd5adf02632b5d4414f\mscorlib.ni.dll
LoadedModule[28]=C:\WINDOWS\System32\ole32.dll
LoadedModule[29]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[30]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
LoadedModule[31]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[32]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System\9340a40c55ba464d0af1399814a708eb\System.ni.dll
LoadedModule[33]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Drawing\83b5be40d31bd05c18e710f0c5118c98\System.Drawing.ni.dll
LoadedModule[34]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Windows.Forms\11878517dd3152d405eed8c5c5d0c552\System.Windows.Forms.ni.dll
LoadedModule[35]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Core\d47bd74620ae94be7f47fd2afefcbe5b\System.Core.ni.dll
LoadedModule[36]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Configuration\691c63248b8b541d0d6a0166b1919ce9\System.Configuration.ni.dll
LoadedModule[37]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Xml\3d19ea2c01651b5c5bffe1ca092d3d8f\System.Xml.ni.dll
LoadedModule[38]=C:\WINDOWS\System32\shell32.dll
LoadedModule[39]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[40]=C:\WINDOWS\System32\shcore.dll
LoadedModule[41]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[42]=C:\WINDOWS\System32\profapi.dll
LoadedModule[43]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[44]=C:\WINDOWS\System32\UMPDC.dll
LoadedModule[45]=C:\WINDOWS\System32\cryptsp.dll
LoadedModule[46]=C:\WINDOWS\System32\bcrypt.dll
LoadedModule[47]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[48]=C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.418_none_71d10a2d5ae97b72\comctl32.dll
LoadedModule[49]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[50]=C:\WINDOWS\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.18362.418_none_5f5edc43821bf931\gdiplus.dll
LoadedModule[51]=C:\WINDOWS\SYSTEM32\DWrite.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
LoadedModule[53]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[54]=C:\WINDOWS\system32\dataexchange.dll
LoadedModule[55]=C:\WINDOWS\system32\d3d11.dll
LoadedModule[56]=C:\WINDOWS\system32\dcomp.dll
LoadedModule[57]=C:\WINDOWS\system32\dxgi.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\dxcore.dll
LoadedModule[59]=C:\WINDOWS\system32\twinapi.appcore.dll
LoadedModule[60]=C:\WINDOWS\system32\RMCLIENT.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\wldp.dll
LoadedModule[62]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[63]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[64]=C:\WINDOWS\System32\WINTRUST.dll
LoadedModule[65]=C:\WINDOWS\SYSTEM32\amsi.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[67]=C:\ProgramData\Microsoft\Windows Defender\platform\4.18.1910.4-0\X86\MpOav.dll
LoadedModule[68]=C:\ProgramData\Microsoft\Windows Defender\platform\4.18.1910.4-0\X86\MPCLIENT.DLL
LoadedModule[69]=C:\WINDOWS\SYSTEM32\gpapi.dll
LoadedModule[70]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Numerics\a804a88e898d4778dd5479deb7da4934\System.Numerics.ni.dll
LoadedModule[71]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Runteb92aa12#\2eacbb1ff8a7bc859ff01b27ad15d0e6\System.Runtime.Serialization.ni.dll
LoadedModule[72]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Data\eee7a155e0aa4926d4076237b42c8751\System.Data.ni.dll
LoadedModule[73]=C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
LoadedModule[74]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[75]=C:\WINDOWS\System32\TextInputFramework.dll
LoadedModule[76]=C:\WINDOWS\System32\CoreUIComponents.dll
LoadedModule[77]=C:\WINDOWS\System32\CoreMessaging.dll
LoadedModule[78]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[79]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[80]=C:\WINDOWS\System32\iertutil.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=18362
OsInfo[3].Key=ubr
OsInfo[3].Value=418
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1031
OsInfo[7].Key=geoid
OsInfo[7].Value=94
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=181220
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.418.18362.0-11.0.155
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=7923
OsInfo[19].Key=svolsz
OsInfo[19].Value=222
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=190318
OsInfo[22].Key=bldtm
OsInfo[22].Value=1202
OsInfo[23].Key=bldbrch
OsInfo[23].Value=19h1_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.18362.418.amd64fre.19h1_release.190318-1202
OsInfo[30].Key=buildflightid
OsInfo[30].Value=<DELETED_BY_ME>
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[33].Key=expid
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=APPCRASH
AppName=YDL-UI
AppPath=D:\Users\<Username>\Desktop\YDL-UI.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=DFBD895793A4E097C24834AA9A364961
MetadataHash=-1091116605

**Comment by Maxstupo** [comment]
Did you have this issue with [v2.5.3](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.5.3)?

**Comment by rolandbeck** [comment]
No, with the v2.6.0 you released yesterday.
v2.5.3 worked (and still works) fine, I am the guy who reported the issue with the regional decimal separator issue. :-)

**Comment by Maxstupo** [comment]
Please try [YDL-UI_Portable_v2.6.0-pb1.zip](https://github.com/Maxstupo/ydl-ui/files/3791951/YDL-UI_Portable_v2.6.0-pb1.zip), and let me know if the issue still occurs.

**Comment by rolandbeck** [comment]
this version works fine, thanks for the quick fix!
