### ISSUE TITLE
New multilanguage interface - Request for changes

### ISSUE THREAD

**Issue by bovirus** [Maxstupo/ydl-ui#46]
@Maxstupo 

![YDL-UI 2 6 0 - 01](https://user-images.githubusercontent.com/1262554/67771370-747e2180-fa58-11e9-991c-afa0d983a6bd.jpg)
![YDL-UI 2 6 0 - 02](https://user-images.githubusercontent.com/1262554/67771371-7516b800-fa58-11e9-84b7-cc8e61fc0fc7.jpg)
![YDL-UI 2 6 0 - 03](https://user-images.githubusercontent.com/1262554/67771372-7516b800-fa58-11e9-8acb-d2578ff4675c.jpg)
![YDL-UI 2 6 0 - 04](https://user-images.githubusercontent.com/1262554/67771373-7516b800-fa58-11e9-96d6-52b3251cf6f2.jpg)
![YDL-UI 2 6 0 - 05](https://user-images.githubusercontent.com/1262554/67771375-7516b800-fa58-11e9-81a7-5f581acb48f8.jpg)

With new multi-language interface there are some issues in some controls because English language is quite shorter than other language.

I attached some screenshots for request for small changes to the interface.
Inlcude also some strings not translated to add to the language.

I made a PR about Italian language.

Thanks.

**Comment by bovirus** [comment]
If you have the space in the GUI to enlarge the UI and use better the corrent UI space, you cannot do it?

**Comment by Maxstupo** [comment]
@bovirus 

I do plan to have the controls automatically resize and/or reposition depending on the length of text. 

This should solve the issue of overlapping text with all languages as the user interface will be able to adapt to the varying length of each string.

**Comment by Maxstupo** [comment]
@bovirus 

Translation entries for screenshots 1,2,3
```
"download_dialog.quality.vq.custom": "Custom",
"download_dialog.quality.fr.custom": "Custom",
"download_dialog.post_processing.audio_only.best": "Best",
```
https://github.com/Maxstupo/ydl-ui_i18n/commit/1f67026697dc7eaef0b93e3336ca52af7781837f

**Comment by bovirus** [comment]
@Maxstupo 

PR Italian language update

https://github.com/Maxstupo/ydl-ui_i18n/pull/3

**Comment by Maxstupo** [comment]
@bovirus 

Controls should now adjust depending on the length of text. Here are a few example screenshots:

![tab_quality_en](https://user-images.githubusercontent.com/6497952/68080749-96f7ac80-fe55-11e9-8afc-a9ebdb2d3911.png)
![tab_quality_it](https://user-images.githubusercontent.com/6497952/68080748-95c67f80-fe55-11e9-809a-b84e6a793ded.png)

-----------------------------

![tab_workarounds_en](https://user-images.githubusercontent.com/6497952/68080757-b989c580-fe55-11e9-9b42-e5e5b8204410.png)
![tab_workarounds_it](https://user-images.githubusercontent.com/6497952/68080759-bd1d4c80-fe55-11e9-8db4-93874324f512.png)

**Comment by bovirus** [comment]
@Maxstupo 

Thanks.
I will wait the new version to test/use it.
