### ISSUE TITLE
Litle Help to the Right Way

### ISSUE THREAD

**Issue by Reset2Root** [Maxstupo/ydl-ui#47]
Unfortunately, I found no other way to give feedback for your software here. Therefore I use this way. If this is wrong, please tell me how it should be. 

I like to use your software, but with every use I ask myself, why does a product, which is meant to contain URLs, need an extra >CLICK< to be able to enter them? 

These belong right at the top and in the last location bar a "drop down" would be nice. Which one remembers it. 

Thank you very much and please continue like this.... 

Regards 

Translated with www.DeepL.com/Translator

**Comment by Maxstupo** [comment]
You can drag and drop URLs into YDL-UI, if this is combined with `Remember Download Settings` and `Auto confirm DragDrop Downloads` the download will be added without the need of an extra click.

Optionally if you are using Firefox you can use the [Open With](https://addons.mozilla.org/en-US/firefox/addon/open-with/) add-on to add URLs to YDL-UI.
