### ISSUE TITLE
YDL-UI 2.6.2 not include Italian language

### ISSUE THREAD

**Issue by bovirus** [Maxstupo/ydl-ui#48]
@Maxstupo 

The latest v. 2.6.2 not include Italian language.

What's the matter?

**Comment by Maxstupo** [comment]
@bovirus 

I wasn't sure if it was ready to be released. I have updated v2.6.2 to include the language.

**Comment by bovirus** [comment]
@Maxstupo 

I downloaded v. 2.6.2 portable and Italian language is not included.

**Comment by Maxstupo** [comment]
@bovirus 

Try downloading  [v2.6.2](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.6.2) again, it should be included.

**Comment by bovirus** [comment]
OK. Thanks.
