### ISSUE TITLE
Fix Speed and ETA column data for a stopped download

### ISSUE THREAD

**Issue by hl2guide** [Maxstupo/ydl-ui#50]
Please fix the Speed and ETA columns not being blank for stopped downloads.

Steps to reproduce the behaviour (if applicable, attach preset file):
1. Download a file
2. Stop the download
3. View data

**Comment by Maxstupo** [comment]
I'm unable to reproduce this issue. Are you using v2.6.3?

Do you mean `stop the download` immediately after being added or after the progress bar starts increasing?

**Comment by hl2guide** [comment]
Example:
![example](https://user-images.githubusercontent.com/17044982/69693802-bb7c3700-112a-11ea-938b-4a74058ddf5a.jpg)
