### ISSUE TITLE
Download failed: Python error

### ISSUE THREAD

**Issue by kissaev** [Maxstupo/ydl-ui#54]
**Download failed**
When i try to download youtube link its failed and in the bottom of the log i see that:

> Fatal Python error: Py_Initialize: unable to load the file system codec
> ImportError: No module named 'encodings'
> 
> Current thread 0x0000185c (most recent call first):

**Information (please complete the following information)**
 - YDL-UI Version: 2.6.3
 - OS: Windows 10 LTSC 1809
 -  Architecture: x64

**Comment by Maxstupo** [comment]
This seems like a youtube-dl issue (maybe relating to Windows 10 LTSC). 

@kissaev 
Have you had YDL-UI working previously?

**Comment by kissaev** [comment]
Youtube-dl works correct from console, YDL-UI installed first time and not works

**Comment by Maxstupo** [comment]
Try replacing `youtube-dl.exe` found in the `bin` folder of YDL-UI with the one that works from console.

**Comment by kissaev** [comment]
> Try replacing `youtube-dl.exe` found in the `bin` folder with the one that works from console.

That was help, thanks
