### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by smaragdus** [Maxstupo/ydl-ui#56]
I came across a YouTube video which [YDL-UI](https://github.com/Maxstupo/ydl-ui) failed to download:

- [YouTube link](https://www.youtube.com/watch?v=q13W_HcLkNM)

**Screen:**

![YDL-UI 2 6 4 - 2020-01-25 - 001](https://user-images.githubusercontent.com/9025757/73116284-76169300-3f3c-11ea-9eb3-d819f16dbabd.png)

Another [youtube-dl](https://ytdl-org.github.io/youtube-dl/) front-end- [Vividl](https://github.com/Bluegrams/Vividl), also failed to get this video:

**Screen:**

![Vividl 0 1 0 0 - 2020-01-25 - error - 001](https://user-images.githubusercontent.com/9025757/73116343-5a5fbc80-3f3d-11ea-8b35-aa2c6b702dd4.png)

But a commercial video downloader managed to get this video:

Screen:

![MP4 Downloader Pro 3 31 1 - 2020-01-25 - 002](https://user-images.githubusercontent.com/9025757/73116356-84b17a00-3f3d-11ea-9b73-931aeef1c3df.png)

I suppose that the problem is within [youtube-dl](https://ytdl-org.github.io/youtube-dl/) but since I encountered this problem I am reporting it.

Can you confirm that [YDL-UI](https://github.com/Maxstupo/ydl-ui) fails to download this particular video?

**Comment by Maxstupo** [comment]
I didn't have an issue. Try updating `youtube-dl.exe` within the `bin` folder, by using the update button in `Settings > Binaries` or manually replacing the file.

**Comment by Ghis1964** [comment]
> 
> 
> I didn't have an issue. Try updating `youtube-dl.exe` within the `bin` folder, by using the update button in `Settings > Binaries` or manually replacing the file.
> 
> If that doesn't fix the issue, the problem is within youtube-dl.

I can confirm.
That's what I did this morning (I'm always only using the bin/command-line) It refused downloading and ask me to update. So, youtube-dl -U, wait for it to complete and than close and re-open, everything went back to normal ☺️👍

**Comment by smaragdus** [comment]
@Maxstupo 

Updating [youtube-dl](https://ytdl-org.github.io/youtube-dl/) really fixed the issue- version **2020.1.1.0** was unable to download the above mentioned video, version **2020.1.24.0** downloaded the video without problem.
