### ISSUE TITLE
Embed thumbnail in mp3

### ISSUE THREAD

**Issue by AndiLeni** [Maxstupo/ydl-ui#58]
Would you consider adding support for yt-download's `--embed-thumbnail` option?
This currently only works with mp3s as ar as I know, but would be a very nice addition f.e. when media is played on smartphones where the background changes to the thumbnail when media is playing.

**Comment by Maxstupo** [comment]
Sure. Most command line arguments for youtube-dl are already supported, they just haven't been exposed in the user interface yet.
