### ISSUE TITLE
Update YDL-UI program (Italian language/youtube-dl/ffmpeg)

### ISSUE THREAD

**Issue by bovirus** [Maxstupo/ydl-ui#59]
**Describe the bug**

Please update application with

- Updated version of YDL-UI Italian language
- Updatef version of youtube-dl.exe
- Updated version of ffmpeg.

**To Reproduce**
Steps to reproduce the behavior (if applicable, attach preset file):

**Expected behavior**

**Screenshots**

**Information (please complete the following information)**
 - YDL-UI Version: [e.g. v1.4.2]
 - OS: [e.g. Windows 7]
 -  Architecture: [e.g. x86, x64]

**Additional context**

**Comment by Maxstupo** [comment]
Release [v2.6.6](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.6.6)
