### ISSUE TITLE
Period of automatic check strings seems not translated

### ISSUE THREAD

**Issue by bovirus** [Maxstupo/ydl-ui#60]
@Maxstupo 

**Describe the bug**

The progranm at first startup seems didn't detect Italin SO and didn'ts etup UI in italian.

In the drop down list of period for automatic check the strings seems are not localized.
Please check the screnshot.

**To Reproduce**
Steps to reproduce the behavior (if applicable, attach preset file):

**Expected behavior**

**Screenshots**

**Information (please complete the following information)**
 - YDL-UI Version: [e.g. v1.4.2]
 - OS: [e.g. Windows 7]
 -  Architecture: [e.g. x86, x64]

**Additional context**

![YDL-UI-2 6 6-01](https://user-images.githubusercontent.com/1262554/82728705-8542fd00-9cf2-11ea-85fd-17adc70dd9f8.jpg)

**Comment by Maxstupo** [comment]
https://github.com/Maxstupo/ydl-ui_i18n/commit/72042c5844acab95526e22729c32990ce9d83e31

**Comment by bovirus** [comment]
@Maxstupo 

Italian language update.

What's about Windows OS language check?
At first startup the program should detect OS language and if it Italian OS detected should set/start automatically with italian language.

**Comment by Maxstupo** [comment]
@bovirus 

Has this just occurred with v2.6.6 or has it been a problem with previous versions also?

**Comment by bovirus** [comment]
I will check.

Which is the path & filename for settings/ini file?

**Comment by Maxstupo** [comment]
If you set the language using the settings window it won't auto-detect the OS language on start.

The settings file is `ydl-ui.json` it's in the same folder as the application. Try setting the language entry to be empty, this should cause YDL-UI to detect the OS language on application startup.

       "Language": "",

**Comment by Maxstupo** [comment]
I think I have found the bug, try [YDL-UI_v2.6.6.3_Portable](https://ci.appveyor.com/api/buildjobs/3skwm5imygsxvmy9/artifacts/YDL-UI_v2.6.6.3_Portable.zip) and see if it detects the language on start.

**Comment by bovirus** [comment]
@Maxstupo 

Thanks. Fixed.
I confirmed that v. 2.6.6.3 detect Italian OS and start in Italian.

**Comment by bovirus** [comment]
@Maxstupo 

I hope to see soon the new version with languages updated and fix for Italian OS check.
