### ISSUE TITLE
Feature request: Download audio section only for youtube

### ISSUE THREAD

**Issue by duytrung** [Maxstupo/ydl-ui#63]
Hello,

I found it possible to download the audio in *.dash format when download clips from Youtube using Jdownloader. Is it possible to implement a function to download audio only with YDL-UI?
JDownload is very bulky with JRE and stuffs. So I do not prefer to use the program otherwise
Thank you very much and hope to hear from you soon.

**Comment by Maxstupo** [comment]
An option for audio only already exists in YDL-UI. 

I'm unsure about downloading dash files, you could try using a custom [format selector](https://github.com/ytdl-org/youtube-dl#format-selection) (Uncheck Basic Mode -> Quality Tab -> Custom Format Selector)

e.g. A selector like `bestaudio` combined with a filter like `protocol` might work.

**Comment by Maxstupo** [comment]
Closing for now. 

Unless this feature is supported in [youtube-dl](https://github.com/ytdl-org/youtube-dl), it can't be implemented in YDL-UI.
