### ISSUE TITLE
[Translation] Russian language

### ISSUE THREAD

**Issue by wvxwxvw** [Maxstupo/ydl-ui#64]
[ru_for_ydl-ui_200614.zip](https://github.com/Maxstupo/ydl-ui/files/4775736/ru_for_ydl-ui_200614.zip)

**Comment by Maxstupo** [comment]
Merged PRs
- https://github.com/Maxstupo/ydl-ui_i18n/pull/8
- https://github.com/Maxstupo/ydl-ui_i18n/pull/9
