### ISSUE TITLE
Restart

### ISSUE THREAD

**Issue by Fot0n** [Maxstupo/ydl-ui#65]
Hello! Thank you for the great program. I want to suggest a function that can be useful. I'm creating a task to download all videos from a Youtube channel. It is executed and terminated. After a while, new videos appear on the channel, which also need to be downloaded. I have to delete an issue and create a new one with the same settings. Is it possible to add "Restart" for completed tasks?

**Comment by Maxstupo** [comment]
Yeah, it should be possible. I will add it in the near future.
