### ISSUE TITLE
Calling name templates should be made more explicit

### ISSUE THREAD

**Issue by wvxwxvw** [Maxstupo/ydl-ui#66]
Calling name templates should be made more explicit. For example, a button.

**Comment by Maxstupo** [comment]
Are you referring to filename templates?

**Comment by wvxwxvw** [comment]
Yes. In the translation, I clarified the method of calling, but it is better to do it more explicitly.

**Comment by Maxstupo** [comment]
Maybe a button similar to the download directory browse button?

![](https://i.gyazo.com/54e73d0b4d6c1e9473a8d0b716b30a11.png)

**Comment by wvxwxvw** [comment]
In my opinion it will be better.

**Comment by wvxwxvw** [comment]
Можно использовать не троеточие, а какой нибудь другой символ, например "˃".

**Comment by Maxstupo** [comment]
https://github.com/Maxstupo/ydl-ui_i18n/commit/a3f66b0538a9469e1dfa8ba76e94d3f5c0f809d6
