### ISSUE TITLE
Some Additional Feature Suggestions

### ISSUE THREAD

**Issue by hydkrash79** [Maxstupo/ydl-ui#67]
Hi @Maxstupo I really love ydl-ui, and have been using it for all my downloads.

Just a couple of suggestions for improvements:
1. File Name Variables - It's missing the option to also utilize the parent folder name as a variable. Sometimes when managing multiple downloads of different videos, this can be a very useful feature.

2. The columns has the download directory, but not the output file name, this could be a useful addition since very often download link names don't make sense, and most people use the filename option. So when downloading along list of files, the only way to know the destination file, is to review the logs one by one while it's downloading.

3. On Windows 10, the column sizing always gets reset, and always have to manually resize.

Providing an image that hopefully can help provide some context around point 2 and 3.
![image](https://user-images.githubusercontent.com/68917626/88695898-1c826180-d135-11ea-89ef-3b391bb22c18.png)

**Comment by Maxstupo** [comment]
1. File name template variables are a part of [youtube-dl](https://github.com/ytdl-org/youtube-dl/tree/2020.06.16.1#output-template) not YDL-UI. This addition would need to be added to youtube-dl.

2. This is something I have wanted to add, unfortunately I haven't found a reliable way of getting the output filename from the log of youtube-dl.

3. I will look into this.

**Comment by hydkrash79** [comment]
Got it. Thanks for looking into this.

**Comment by Maxstupo** [comment]
Do you mean the column width is getting reset?
Is it happening when opening YDL-UI or adding/removing columns?

**Comment by hydkrash79** [comment]
The column widths are getting reset when YDL-UI is being restarted.

**Comment by Maxstupo** [comment]
Are any settings being reset at startup (in the settings window)?

**Comment by hydkrash79** [comment]
Nope. Those are fine. For e.g. after changing the max concurrent downloads, that stays.
Oh ok, I think I know what's the issue.
It's not so much the columns don't keep their width.
After the window is resized, restarting the app, causes it to go back to the original size, and thus resulting in the columns resizing as well.

**Comment by Maxstupo** [comment]
Hmm, that shouldn't be the cause. The column width(s) are saved as a percentage of the window width. So the size of the window shouldn't matter.

**Comment by hydkrash79** [comment]
Ah I see. I guess it should be ok then. Sorry for the trouble.
