### ISSUE TITLE
Change auto-updater to use YT-DLC 

### ISSUE THREAD

**Issue by ScottRFrost** [Maxstupo/ydl-ui#71]
While youtube-dl fights of the RIAA's bunk DMCA claims, it should be pretty simple to point YDL-UI's auto updater at https://github.com/blackjack4494/yt-dlc

The current release (as of 10/29) fixes YouTube issues.

**Comment by ScottRFrost** [comment]
Youtube-DL is back up on GitHub, so this can now be reverted if you'd like (even though YT-DLC has more frequent updates)

**Comment by Maxstupo** [comment]
[v2.6.12](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.6.12) reverted it.
