### ISSUE TITLE
Consider using calendar versioning

### ISSUE THREAD

**Issue by Maxstupo** [Maxstupo/ydl-ui#72]
Since YDL-UI is very dependent on other applications that are continuously changing (e.g. youtube-dl), it might be sensible to use [calendar versioning](https://calver.org/) for future releases.

The two major changes needed to support calendar versioning will be adjusting how the `Check for Updates` feature compares version strings, and updating the AppVeyor config to support automatic calendar versioning.

E.g. Something like below - Format of `YY.0M.BUILD`
```
init:
  - ps: $env:padded_build_number = ([int]$env:appveyor_build_number).ToString("00")
  - ps: Update-AppveyorBuild -Version "$(Get-Date -format yy.MM).$env:padded_build_number"
```

**Comment by smaragdus** [comment]
@Maxstupo 

I prefer the current sequence versioning scheme than the release date vesrioning scheme as the latter hints nothing at the age and maturity of a program. Also, the [youtube-dl](https://yt-dl.org/) executable (**youtube-dl.exe**) can be updated manually.

**Comment by Maxstupo** [comment]
Yeah, those are good points. 

I think for the time being I will keep the current versioning scheme (and go with the _if it ain't broke, don't fix it_ philosophy). The issue can be opened again if needed.
