### ISSUE TITLE
youtube-dl is updated with the -U parameter

### ISSUE THREAD

**Issue by wvxwxvw** [Maxstupo/ydl-ui#73]
youtube-dl is updated with the -U parameter. Current version 201101.1.

**Comment by Maxstupo** [comment]
@wvxwxvw 

What is the issue?

**Comment by wvxwxvw** [comment]
In that

> Switched to using yt-dlc while the official youtube-dl repository is unavailable.

Why fork if the original update works? What is the advantage?

**Comment by Maxstupo** [comment]
For me the [original](https://github.com/ytdl-org/youtube-dl)`-U` update doesn't work. 

![](https://i.gyazo.com/967710096506b9087bb344217e8d762d.png)

You can always replace the original packaged `youtube-dl.exe` with whatever version you want.

**Comment by wvxwxvw** [comment]
> For me the original-U update doesn't work.  

Is it worth using the correct DNS?
https://www.dnscrypt.org/

> You can always replace the original packaged youtube-dl.exe with whatever version you want.  

Judging by the forums, I'm not the only one, no one wants to use forks while the original is available.
Updating doesn't really work from the GUI, but it does from the command line. Why?
![111](https://user-images.githubusercontent.com/13194155/97964112-45b42d00-1dc9-11eb-9937-e8bbc0e12641.gif)

**Comment by Maxstupo** [comment]
> Is it worth using the correct DNS?
> https://www.dnscrypt.org/

Looks like I couldn't update on my end (SSL: CERTIFICATE_VERIFY_FAILED) 

`youtube-dl.exe -U --no-check-certificate` temporarily fixed the problem.

---
I was using a fork as I wasn't aware the original was still available, so I will switch back to using it.

Do you know where the source is hosted for the original? It couldn't be the original GitHub repository as that was taken down.

**Comment by wvxwxvw** [comment]
Sources?
Isn't it at the end of the page?
https://pypi.org/project/youtube_dl/#files
