### ISSUE TITLE
detected as trojan by windows defender. 

### ISSUE THREAD

**Issue by milindgoel15** [Maxstupo/ydl-ui#75]
**Describe the bug**
Its not related to UI/UX or crashes or anything like that but when i downloaded and extracted, it was detected as trojan by defender. Ik its open source and i can look up all its code but idk any part how to look cuz i am not a coder and have 0 coding skills(as i not from this field of work). but can u help me with this issue? 

**To Reproduce**
Steps to reproduce the behavior (if applicable, attach preset file):
Download, extract and start downloading yay but :(

**Screenshots**
![2020-11-15](https://user-images.githubusercontent.com/45682747/99156896-ce489c80-26ea-11eb-9224-004dc4de399c.png)

**Information (please complete the following information)**
 - YDL-UI Version: v2.6.12-_portable from github
 - OS: windows 10 2004 update
 -  Architecture: x64

**Additional context**
none

**Comment by Maxstupo** [comment]
It looks like a false positive with Windows Defender (seems like others have had [similar issues](https://github.com/damienhaynes/TraktRater/releases/tag/2.3.10), see nb)

https://www.virustotal.com/gui/file/858809656eed91273b44e371cf97d5f53ffb13b7aeeb85125b373c996ce61d57/detection

It's up to you but you can always ignore the detection.

**Comment by milindgoel15** [comment]
👍👍

**Comment by TechTrooper** [comment]
![image](https://user-images.githubusercontent.com/3955313/100891074-9189ed00-34c1-11eb-9868-2c20e189ee72.png)

Seems like a few more engines detected it too.
