### ISSUE TITLE
cant install 2.6.12

### ISSUE THREAD

**Issue by solidspartan** [Maxstupo/ydl-ui#76]
I downloaded the source.zip file and cant install ydl-ui. What file am I supposed to click on because the install wiki doesn't help?

**Comment by Maxstupo** [comment]
You need `YDL-UI_v2.6.12.0_Portable.zip` instead of `Source code (zip)`. 

ydl-ui is portable so it doesn't need to be installed only unzipped. Unzip `YDL-UI_v2.6.12.0_Portable.zip` then click on the `YDL-UI.exe` file.

**Comment by pschonmann** [comment]
Probably caused, that Antivirus dont extract zip, because its triggered.
https://www.virustotal.com/gui/file/052a1bc6e05a3cf19e322a485a18965d7484cccf2bcdfb886550d8de0f5e71d7/detection
