### ISSUE TITLE
Windows Defender Alert

### ISSUE THREAD

**Issue by mRUshh** [Maxstupo/ydl-ui#78]
Windows considers ydl-ui to be a Trojan virus: **Trojan:MSIL/Masslogger.VN!MTB**. "This program is dangerous and follows the attacker's instructions.". Moved these files to quarantine:
file: C:\Portable\YDL-UI_v2.6.12.0_Portable\YDL-UI.exe
file: C:\Users\mariu\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\YDL-UI.lnk
startup: C:\Users\mariu\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\YDL-UI.lnk

So the program file and the shortcut in the Start menu are gone. I don't know if I can trust this program and restore the file, Youtube-DLG is clean and it is intended for the same.

My operating system: Windows 10 Home 20H2 (19042.630).

**Comment by nanohtpc** [comment]
same here

**Comment by Maxstupo** [comment]
https://github.com/Maxstupo/ydl-ui/issues/75#issuecomment-727446667
