### ISSUE TITLE
columns resizing to unusable sizes

### ISSUE THREAD

**Issue by k4rsus** [Maxstupo/ydl-ui#79]
I have been dealing with the issue of after reopening the application after having had it open previously in the same session that the columns for the title, speed, ETA etc all collapse into the smallest possible size. 
I am not entirely sure it's tied to restarting the application within the same session but I noticed that is when it's most prone to happen then

v2.6.12
Win 10

![the problem](https://user-images.githubusercontent.com/75054734/100378707-9cd0aa80-2fe1-11eb-8c93-f9bcb773e15c.png)

That aside, I love your work and thank you for maintaining it

**Comment by Maxstupo** [comment]
This is an intermittent bug that has been around for a bit. It seems to cause issues for some and not others.

It's indeed tied to the restarting of the application, as it's related to remembering the column widths stored in the `ydl-ui.json` file. 

I'm considering removing the column width saving as it hasn't been that advantageous, and would fix this problem.
