### ISSUE TITLE
Option to continue jobs that were running when the program was shut down last time

### ISSUE THREAD

**Issue by awgiedawgie** [Maxstupo/ydl-ui#8]
Currently, when the program opens, if there are any jobs that were running when the program was shut down last time, they are automatically started up again, either to continue where they left off, or to restart the download if the temporary files have been deleted.

It would be nice to have a pop-up upon opening the program, giving the option whether to start running those jobs again. Alternately, there could be a setting in Preferences that would apply globally every time the program opens.

On a related note, it would also be nice to have a way to cancel a running job. Say you start downloading a video, and discover that it's going to be 8GB, so you decide you want to stop it. Such as adding an option to the menu that pops up when you right-click on a job. Currently, the only way to cancel a running job is to close the program. But, as mentioned above, the next time you open the program, the job will just start up again, so that's not really effective.

**Comment by Maxstupo** [comment]
Having a stop option in the right-click download menu would be nice. 

I think prompting on startup wouldn't be needed if the download once stopped didn't automatically restart upon opening the program.

**Comment by smaragdus** [comment]
@awgiedawgie 
Thank you for suggesting 'Cancel' option- I was about to request it but I was busy and later forgot about it.

@Maxstupo 
I suppose 'Cancel' won't be too hard to be implemented.

Merry Christmas to both of you!
