### ISSUE TITLE
detected as a virus 

### ISSUE THREAD

**Issue by moonmuaaz000** [Maxstupo/ydl-ui#80]
detected as a virus by BitDefender. 

here is virus total result 
https://www.virustotal.com/gui/file/858809656eed91273b44e371cf97d5f53ffb13b7aeeb85125b373c996ce61d57/detection
detected as virus by 15 out of 64

Edit: i know people didnt like this issue i know i can see the source code i am not expert in C# i am sharing this project on reddit and some user complained that it is being detected as a virus and then i verified it myself
https://www.reddit.com/r/youtubedl/comments/j954xy/late_2020_whats_the_best_youtubedl_gui/
"Skip this one. Couldn't even get the zip open because there were two Trojan injectors inside" - u/wavetro

i have been using this project for a long time and encouraging people to use this but it is being detected as trojan virus now i would like developers to notice this issue even if its not much of a issue for other C# developers but it is for normal end users which is preventing people like wavetro to use it to full extend.

**Comment by Maxstupo** [comment]
I agree that it's an issue for end users. Unfortunately not much can be done (other than compiling the source yourself, but not everyone can do that).

It seems like release [v2.6.13](https://github.com/Maxstupo/ydl-ui/releases/tag/v2.6.13) may have fixed the false positives.
https://www.virustotal.com/gui/file/337b09ea865db54cea191653d5b4031232686db7b5dd4f1160cb8047caf9bef9/detection

**Comment by moonmuaaz000** [comment]
thanks i appreciate all your effort. Glad it is not overlooked. For now i will stick with v2.6.13 for privacy reasons
