### ISSUE TITLE
Enhancements - layout tweaks

### ISSUE THREAD

**Issue by Nuthin** [Maxstupo/ydl-ui#81]
**Describe the bug**
Hello, a few minor tweaks or suggestions that would make this much easier to use:

// These are all in relation to the "Add Download" screen (top screenshot)
1) The dropdown to select between configurations seems to have shrunk from what's shown in the example screenshot.  It's too narrow to read a decent length of text in the profile name, so was hoping you could make the dropdown wider?
2) Somewhere in one of the tabs or on a new tab, it would be helpful to display the commandline that is being generated based on the selected options
3) Re-arrange the controls on each of the 4 tabs.  It's a bit confusing that on the "Quality" tab, there is a "File System" section, "General" section (which don't have anything to do with "Quality".   Should the "File System" ones not belong on the "Post Processing" tab?
4) There's a write thumbnail in the File System section and an Embed Thumbnail in the post processing?  Maybe this should be moved to a new tab and call it "Output" or something?  (Or maybe make a combined Post Processing / Output tab since that one is half empty?
5) If you create a tab called "Output" the Download Directory and Filename Template and Download Archive can be moved from the top of the screen to reduce clutter
6) Make the "Add" button the default instead of Cancel

// In relation to the main window (second screenshot)
1) The menus are very confusing because the "File Menu" has 1 option in it, yet the "Settings Menu" Also has 1 option, yet activates immediately as if it's a button.  In reality, the menu contains so few items, that it would probably be best served with a toolbar.  Would it be possible to change to a toolbar instead of menus?
2) When you right click on the empty area of the background (context menu) and in the Download menu, can we have a "clear all" option?  (to clear all the completed downloads, not the logs).

// Not shown in screenshot
1) Would it be possible to have a setting to automatically clear completed downloads?

Keep up the good work

**Screenshots**
![2021-01-21_01h31_19](https://user-images.githubusercontent.com/77774816/105320117-68194380-5b8b-11eb-9652-27fdfc8ae5e7.png)

![2021-01-21_02h09_48](https://user-images.githubusercontent.com/77774816/105322004-d828c900-5b8d-11eb-9e25-e59d673737b6.png)

**Information (please complete the following information)**
 - YDL-UI Version: 2.6.13
 - OS: W10
 -  Architecture: x64

**Additional context**

**Comment by Maxstupo** [comment]
>    The dropdown to select between configurations seems to have shrunk from what's shown in the example screenshot. It's too narrow to read a decent length of text in the profile name, so was hoping you could make the dropdown wider?

I'll attempt to make the width automatic like the majority of other controls.


>    Somewhere in one of the tabs or on a new tab, it would be helpful to display the commandline that is being generated based on the selected options

A command-line preview should be possible.

>    Re-arrange the controls on each of the 4 tabs. It's a bit confusing that on the "Quality" tab, there is a "File System" section, "General" section (which don't have anything to do with "Quality". Should the "File System" ones not belong on the "Post Processing" tab?

>    There's a write thumbnail in the File System section and an Embed Thumbnail in the post processing? Maybe this should be moved to a new tab and call it "Output" or something? (Or maybe make a combined Post Processing / Output tab since that one is half empty?

 > If you create a tab called "Output" the Download Directory and Filename Template and Download Archive can be moved from the top of the screen to reduce clutter

 The layout could do with a rework, initially it was following the pattern of [youtube-dl's help page](https://github.com/ytdl-org/youtube-dl/tree/2021.01.16#options) `youtube-dl.exe --help`

>    Make the "Add" button the default instead of Cancel

The `Add` button is the default when enabled.

> When you right click on the empty area of the background (context menu) and in the Download menu, can we have a "clear all" option? (to clear all the completed downloads, not the logs).

You mean clear the items in the download list but keep the `View Log` data of the download items? If so, that isn't possible as the console log data is stored with each download item.

> Would it be possible to have a setting to automatically clear completed downloads?

It would be possible. A delay before clearing might be a good idea. e.g. `download completes > wait x minute(s) > remove from download list`

**Comment by Nuthin** [comment]
1) This would be great!

2) This would be great!

3) Ahh I see how the labeling follows the sections, but I think it's as much the label itself, but rather how YDL-UI groups the labels.  For example the "File System" group is on the "Quality" tab in YDL-UI, but in help it's listed as an equal level heading.  Ex. I would suggest either:
- Lumping ALL the options onto 1 large page
- Rework the existing 4 tabs to be a bit more intuitive in how they are labeled in which groups are on each screen in terms of how people think about configuring things instinctively (ex. open up MS Word and look how the ribbons are organized or the options are categorized). I guess it could be described as more by function/category?
- Break the existing groups into a few more tabs, so that the tabs directly correlate with the help document.

4) Sorry you're right about the add button.  Not sure how it somehow got out of that state.

5) No I meant more of a #6 thing.  Maybe two separate options 1) clear entire download list (wiping out the entire list even if it has pending downloads or files that have errored 2) clear completed downloads (for people who don't want to enable an auto clear setting, for the same purpose.  Both of these would delete the associated "view log".

6) this would be great, but would like at least some options in the seconds range if you're going to hardcode a list.  Even for people like me (who want the list to be clear when there are no files that have errored and everything is downloaded) I can see the value of it sticking around on the screen for 5,10,15 seconds maybe as a visual indication.  I can also see some people wanting 1, 2, 5, 15, 30, 60 min, 2,3,6,12,24 hours 2,3,5,7 days maybe if you wanted to hard-code options.  Easiest route would probably be a freetext box to auto-remove after X seconds (or if you wanted to get fancy a freetext box for numeric  value and dropdown for units (seconds/minutes/hours/days).  (although I think if the program is geared towards more advanced users ex. that understand regex) they are probably used to calculating time values in seconds (or ms) so the extra work isn't necessary.

**Comment by Maxstupo** [comment]
> No I meant more of a #6 thing. Maybe two separate options 1) clear entire download list (wiping out the entire list even if it has pending downloads or files that have errored 2) clear completed downloads (for people who don't want to enable an auto clear setting, for the same purpose. Both of these would delete the associated "view log".

1. Multi download removal is already supported with `Ctrl+A`, `dragging`, or `Ctrl+Click`.
2. Clearing completed downloads is already possible with `Download Menu > Select > Completed Download(s)` but takes longer than ideal. Adding an option to clear completed downloads under the download menu might be a better place (alongside the Clear Logs option).

**Comment by Maxstupo** [comment]
Closing issue as major enhancements/tweaks have been implemented.

If needed, new issues can be opened regarding specific enhancements described.
