### ISSUE TITLE
A programm look blurry (laptop 141 ppi).

### ISSUE THREAD

**Issue by abactuon** [Maxstupo/ydl-ui#86]
A programm look blurry (laptop 141 ppi).
"High DPI scalling override" in Windows 10 does not help.

**Comment by Maxstupo** [comment]
Try setting font scaling to 100%. Currently, YDL-UI isn't DPI aware, and has issues when using font scaling that isn't the default.

If this doesn't fix it, not much can be done until YDL-UI is made DPI aware (which has no ETA at the moment).
