### ISSUE TITLE
Feature Request : MultiThread downloading , Clipboard monitoring

### ISSUE THREAD

**Issue by mohitmeanslove** [Maxstupo/ydl-ui#88]
List of features

**1: Multithread Downloading/ Connections per Download** : Kindly provide this option so that video will be download in fast way. This function has already been existed in firedm whose developer is also on github.
Screenshot of " Connection per Download " in firedm Software
![dd](https://user-images.githubusercontent.com/84594515/121127858-0d396d80-c848-11eb-8f55-d4e2c503fa0c.png)

**2Thumbnail Issue**: Thumbnail always get download in Webp format. It should be in jpg or jpeg or Png like firedm software always download thumbnail in PNG.

3)**Clipboard Monitoring and download automatically** : When a person copy a youtube link then it should get download automatically without any prompt. This feature already exist in byclick youtube downloader,Mediahuman youtube downloader etc.
Screenshot of Autodetect feature of byclick youtube downloader software
![120233028-74688800-c272-11eb-9772-cacc8d29b88a](https://user-images.githubusercontent.com/84594515/121127635-b0d64e00-c847-11eb-8923-7f56a6a83cff.png)

**4)Try to use Yt-dlp in future updates** : Though i am not an expert But as far as my little knowledge which i have , I found that Yt-dlp gives more options and better than Youtube-dl. In the latest release of Yt-dlp, Developer has merged youtube-dl into yt-dlp. You can check the [release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2021.06.01)

Btw firedm software gives both options. You can use youtube_dl and Yt_dlp as per your wish.
![120720238-5d7f9b00-c4e9-11eb-813f-6c24896571d2 (1)](https://user-images.githubusercontent.com/84594515/121127799-f4c95300-c847-11eb-91a8-9f38f464c1f7.png)

**Comment by Maxstupo** [comment]
> 1: Multi-thread Downloading/ Connections per Download

My understanding is that youtube-dl doesn't support multi-threaded downloading.


> Thumbnail Issue: Thumbnail always get download in Webp format. It should be in jpg or jpeg or Png like firedm software always download thumbnail in PNG.

YDL-UI is only a GUI for youtube-dl, downloading thumbnails uses the [`--write-thumbnail`](https://github.com/ytdl-org/youtube-dl/tree/2021.06.06#thumbnail-options) flag, image format is determined by youtube-dl. Unless an option is available in youtube-dl to change thumbnail format, it won't be implemented.


> Clipboard Monitoring and download automatically

This sounds interesting, but what stops it from downloading non-downloadable URLs? Or is it only for YouTube URLs?

> Try to use Yt-dlp in future updates

YDL-UI was made for youtube-dl. You are free to change what distribution of youtube-dl is used by YDL-UI. See `Settings > Binaries`.

Never heard of FireDM

**Comment by mohitmeanslove** [comment]
> > Clipboard Monitoring and download automatically
> 
> This sounds interesting, but what stops it from downloading non-downloadable URLs? Or is it only for YouTube URLs?
> 
It works for youtube URLs and other supportive websites. I recommend you to provide atleast for youtube URLs in your next update so  whenever someone copy a youtube URL then the software downloads the video without any prompt.

**Comment by smaragdus** [comment]
@Maxstupo 

> Never heard of FireDM

This is [FireDM](https://github.com/firedm/FireDM)- a general purpose download manager based on LibCurl which also supports youtube-dl, written in Python.
