### ISSUE TITLE
https://www.virustotal.com/gui/file/13b51734dc5422a4d38d1df45fe8ebd0cc042cb3dcecba79cbe85a8d7c7df4aa/relations

### ISSUE THREAD

**Issue by Githopp192** [Maxstupo/ydl-ui#89]
https://www.virustotal.com/gui/file/13b51734dc5422a4d38d1df45fe8ebd0cc042cb3dcecba79cbe85a8d7c7df4aa/relations

![ScreenShot008](https://user-images.githubusercontent.com/32612067/121215088-fadb2600-c87f-11eb-83dc-a581b7a7f1d0.jpg)
![ScreenShot009](https://user-images.githubusercontent.com/32612067/121215179-13e3d700-c880-11eb-9fdd-edaaf29ca764.jpg)

**Comment by Maxstupo** [comment]
It's a false positive. Releases are built on [AppVeyor](https://ci.appveyor.com/project/Maxstupo/ydl-ui) making it unlikely that it's infected.
