### ISSUE TITLE
Post Processing

### ISSUE THREAD

**Issue by smaragdus** [Maxstupo/ydl-ui#9]
After I add a download link with 2160p (4K) (Ultra-HD) quality and in Post Processing set Recode Format to Mp4 processing never finishes and ffmpeg.exe uses about all CPU resources (97.83%) so I have to terminate the process tree. It seems that the processing has finished but status still shows Processing. This happens all the time I choose these parameters. Can you confirm the problem?

**Comment by Maxstupo** [comment]
The "processing" status is shown when ffmpeg is running. It's normal for the CPU usage to be that high as it's recoding the video. The processing time can take seconds to hours depending on your computer speed, and the length/quality of the video.

You could alternatively use a different program to recode downloaded videos such as [HandBrake](https://github.com/HandBrake/HandBrake).

**Comment by smaragdus** [comment]
@Maxstupo 

OK, feel free to close this issue. I am not a ffmpeg specialist but using different front-ends for ffmpeg never caused so high CPU usage. However the videos I tried to re-encode were not that big (60-100 MB).
