### ISSUE TITLE
Please support aria

### ISSUE THREAD

**Issue by 10362227** [Maxstupo/ydl-ui#90]
Please support ARIA
`custom arguments:  --external-downloader "aria2c" --external-downloader-args "-x 16 -k 1M" `
but no work

**Comment by Maxstupo** [comment]
What's the advantage of supporting aria2c? youtube-dl seems perfectly suitable for downloading.

What's not working? It should still work, just the columns in the download list won't update.

Have you placed `aria2c.exe` into the same directory of `youtube-dl.exe`?

**Comment by 10362227** [comment]
it works, but the progress bar didn't show any progress

**Comment by Maxstupo** [comment]
Closing issue from lack of information. I don't plan on adding support for aria2c in the download list.
