### ISSUE TITLE
Feature Request: Automatic Retries for failed Downloads

### ISSUE THREAD

**Issue by ErdLingMS** [Maxstupo/ydl-ui#91]
When a download task fails, one has to right click the task in the list and click on "Start" to resume it. Depending on circumstances, this has to be done multiple times for one task.

My suggestion is to add an option to automatically do this.

Note that this is apparently different to the already present retry options ("Retries" and "Fragment Retries") in the Workaround tab. What I am requesting is not a command line argument passed to ytdl, but something the UI should be doing "one level of abstraction higher". Basically, automatically activating the right-click "Start" command. 

It is not a replacement to the already present (above mentioned) options, nor should it be, but rather a complement to them. (It would also jive perfectly with the already present Sleep Interval setting.)

**Comment by Maxstupo** [comment]
When would a situation like this arise? Typically, if a download fails, it's not something that can be resolved by simply restarting the download.

**Comment by ErdLingMS** [comment]
Oh yes it does. Typical situation is downloading a Youtube video of high length (60+ minutes). The download is interrupted multiple times. Just restarting the download will continue the task at the point it left off. I encounter this regularly. 

Maybe my wifi connection that is the issue here. However, it also may be some kind of "copy protection" by Youtube, because if I limit the download speed to around 300 KiB/s, it rarely stops, but if the download is very fast, like 2-5 MiB/s, it will stop very frequently.
