### ISSUE TITLE
Import option of CSV

### ISSUE THREAD

**Issue by hydkrash79** [Maxstupo/ydl-ui#96]
I see that there is now an import feature.
It would be great if it took a CSV file format.
Where we could possibly import things like the filename (with the variables supported by ydl), folder path, etc. 

This will truly enable a bulk upload functionality.

**Comment by Maxstupo** [comment]
I like the idea, but it would require a large rewrite of the existing import code. Currently, I have very little free time to work on YDL-UI.

If you use [presets](https://github.com/Maxstupo/ydl-ui/wiki/Presets) with URL matching and [filename template variables](https://github.com/Maxstupo/ydl-ui/blob/51fa1eb0cc2b31391a78601a82132beaae5ee526/Screenshots/YDL-UI_v2.2.0_FilenameTemplate.gif), you shouldn't really need to specify folder paths and filenames during import.
