### ISSUE TITLE
MPD & M3U8 Stream Link Not Work with this GUI (v.2.8.1 - Newest Ver)

### ISSUE THREAD

**Issue by phanluchoaofficial20** [Maxstupo/ydl-ui#97]
**Describe the bug**

I have use your GUI and start download with any mpd or m3u8 stream link but they all not work, they have the error when extracting the mpd link (no video formats found). I dont know why, do you have any solution for this ?

**To Reproduce**
Steps to reproduce the behavior (if applicable, attach preset file):

**Expected behavior**

**Screenshots**

**Information (please complete the following information)**
 - YDL-UI Version: v.2.8.1
 - OS: Windows 11 Pro 21h2
 -  Architecture: x64

**Additional context**

**Comment by Maxstupo** [comment]
YDL-UI is just a GUI for [youtube-dl](https://github.com/ytdl-org/youtube-dl). So if youtube-dl doesn't support that format/url, it won't work in YDL-UI either. 

I'm not sure about MPD urls, but from my experience, m3u8 urls don't reliably download with youtube-dl. You could try using ffmpeg.

**Comment by phanluchoaofficial20** [comment]
> YDL-UI is just a GUI for [youtube-dl](https://github.com/ytdl-org/youtube-dl). So if youtube-dl doesn't support that format/url, it won't work in YDL-UI either.
> 
> I'm not sure about MPD urls, but from my experience, m3u8 urls don't reliably download with youtube-dl. You could try using ffmpeg.

Thanks!
