### ISSUE TITLE
How to mux video and audio-setting?

### ISSUE THREAD

**Issue by Usulyre** [Maxstupo/ydl-ui#98]
Is there  a setting to mux video and audio together, everytime I download a video the result is separate video file and a separate audio file, but i don't see any setting for joining after download?

**Comment by Maxstupo** [comment]
The default behaviour of YDL-UI should mux audio and video together. Are you using a custom format selector?

**Comment by Usulyre** [comment]
I might have been, but I set everything back to defaults and the video and audio are joined now. Thanks for replying.
