### ISSUE TITLE
ERROR: AtomicParsley was not found. Please install.

### ISSUE THREAD

**Issue by farshad991** [Maxstupo/ydl-ui#99]
hello 
I get this error in log when enabling the Embed Thumbnail
I downloaded the AtomicParsley but I do not know where to put it

**Comment by Maxstupo** [comment]
You could try placing the file in the `bin` folder that contains `youtube-dl.exe` or the `bin/ffmpeg` folder.

This is an issue to do with youtube-dl and not YDL-UI. So you should ask over on the youtube-dl repository.

**Comment by farshad991** [comment]
I copied the file to the bin folder and it work, thank you.
